### ISSUE TITLE
deadbolt-scala_2.11;2.5.0-SNAPSHOT: not found

### ISSUE THREAD

**Issue by intracer** [schaloner/deadbolt-2-scala-examples#3]
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: be.objectify#deadbolt-scala_2.11;2.5.0-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::

**Comment by schaloner** [comment]
PR merged, thanks!
